#!/bin/bash

sort -mu                                        \
    <(7z x -so pwned-passwords-1.0.txt.7z)      \
    <(7z x -so pwned-passwords-update-1.txt.7z) \
    <(7z x -so pwned-passwords-update-2.txt.7z) \
    | ./hex2bin > pwned-passwords.bin
